// <auto-generated />
using System;
using BattleGame.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BattleGame.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240220151903_TimeFinishedNullable")]
    partial class TimeFinishedNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BattleGame.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MinesCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TimeCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TimeFinished")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("BattleGame.Models.GameField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<bool>("HasMine")
                        .HasColumnType("boolean");

                    b.Property<int>("MinesAround")
                        .HasColumnType("integer");

                    b.Property<bool>("Revield")
                        .HasColumnType("boolean");

                    b.Property<int>("posX")
                        .HasColumnType("integer");

                    b.Property<int>("posY")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("GameFields");
                });

            modelBuilder.Entity("BattleGame.Models.GameField", b =>
                {
                    b.HasOne("BattleGame.Models.Game", "Game")
                        .WithMany("GameFields")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("BattleGame.Models.Game", b =>
                {
                    b.Navigation("GameFields");
                });
#pragma warning restore 612, 618
        }
    }
}
